# Generated by Django 4.2.1 on 2023-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='is_avilable',
            field=models.BooleanField(default=True),
        ),
    ]
