# Generated by Django 4.2.1 on 2023-05-11 12:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_borrowedbook_book_remove_borrowedbook_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10, validators=[core.validators.ISBNValidator]),
        ),
    ]
