# Generated by Django 4.2.1 on 2023-05-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='managed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
